
```{r setup}
library(tidyverse)
library(synExtra)
library(here)

synapser::synLogin()
syn <- synExtra::synDownloader("~/data/DGE_comp/")

wd <- here("read_inventory")
dir.create(wd, showWarnings = FALSE)
```


```{r loading}
datasets <- syn("syn21544261") %>%
  read_rds()

fastq_counts <- syn("syn21542323") %>%
  read_csv()

dataset_names <- syn("syn21641420") %>%
  read_csv()
```


```{r assemble_stats}
count_stats <- datasets %>%
  gather(key = "count_type", "count", counts, count_dupes, barcode_counts) %>%
  mutate(
    count = map(
      count,
      ~.x %>%
        group_by(sample_id) %>%
        summarize(count = sum(count)) %>%
        ungroup()
    )
  ) %>%
  unnest(count)

dataset_stats <- count_stats %>%
  drop_na(sample_id) %>%
  group_by(dataset, batch, plate, count_type) %>%
  summarize(count = sum(count)) %>%
  ungroup() %>%
  mutate_at(vars(plate), as.numeric) %>%
  bind_rows(
    fastq_counts %>%
      transmute(dataset, batch, plate, count_type = "fastq_count", count = fastq_count)
  ) %>%
  mutate(
    count_type = factor(count_type, levels = c("fastq_count", "barcode_counts", "count_dupes", "counts"))
  ) %>%
  arrange(dataset, batch, plate, count_type) %>%
  group_by(dataset, batch, plate) %>%
  mutate(
    count_fraction = count / count[[1]],
    count_prev_fraction = count / c(count[[1]], head(count, -1)),
    count_lowest_class = count - c(count[-1], 0),
    count_lowest_class_fraction = count_lowest_class / count[[1]]
  ) %>%
  ungroup()

# combined_stats <- count_stats %>%
  

```


```{r plot_count_stats}

count_names <- tribble(
  ~count_type, ~count_type_name,
  "fastq_count", "reads",
  "barcode_counts", "assigned reads",
  "count_dupes", "gene counts",
  "counts", "deduplicated gene counts"
) %>%
  mutate(
    count_type_name = as.factor(count_type_name) %>%
      fct_inorder() %>%
      fct_rev()
  )

dataset_stats_bars <- dataset_stats %>%
  inner_join(dataset_names) %>%
  inner_join(count_names) %>%
  mutate(dataset_name = fct_cross(dataset_name, as.factor(plate) %>% fct_inseq(), sep = "_")) %>%
  ggplot(aes(dataset_name, count_prev_fraction, fill = count_type_name)) +
    geom_col(position = "dodge") +
    coord_flip() +
    scale_fill_discrete(breaks = rev(levels(count_names$count_type_name))) +
    # scale_y_discrete(limits = rev(levels(count_names$count_type_name))) +
    labs(y = "Fraction of reads", x = "Dataset", fill = "")

ggsave(
  file.path(wd, "relative_fraction_reads_bar.png"),
  dataset_stats_bars, width = 8, height = 4
)


dataset_remaining_stats_bars <- dataset_stats %>%
  inner_join(dataset_names) %>%
  inner_join(count_names) %>%
  mutate(dataset_name = fct_cross(dataset_name, as.factor(plate) %>% fct_inseq(), sep = "_")) %>%
  ggplot(aes(dataset_name, count_fraction, fill = count_type_name)) +
    geom_col(position = "dodge") +
    coord_flip() +
    scale_fill_discrete(breaks = rev(levels(count_names$count_type_name))) +
    # scale_y_discrete(limits = rev(levels(count_names$count_type_name))) +
    labs(y = "Fraction of reads", x = "Dataset", fill = "")

ggsave(
  file.path(wd, "cumulative_fraction_reads_bar.png"),
  dataset_remaining_stats_bars, width = 8, height = 4
)

dataset_stats_bars_abs <- dataset_stats %>%
  inner_join(dataset_names) %>%
  inner_join(count_names) %>%
  mutate(dataset_name = fct_cross(dataset_name, as.factor(plate) %>% fct_inseq(), sep = "_")) %>%
  ggplot(aes(dataset_name, count, fill = count_type_name)) +
    geom_col(position = "dodge") +
    coord_flip() +
    scale_fill_discrete(breaks = rev(levels(count_names$count_type_name))) +
    # scale_y_discrete(limits = rev(levels(count_names$count_type_name))) +
    labs(y = "Number of reads", x = "Dataset", fill = "")

ggsave(
  file.path(wd, "absolute_reads_bar.png"),
  dataset_stats_bars_abs, width = 8, height = 4
)


```


