---
title: "Query Clue CMap drug sets"
author: "Clemens Hug"
date: "7/2/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
# library(genebabel)
library(biomaRt)
library(clueR)
library(synExtra)
library(here)
library(data.table)
library(cmapR)

synapser::synLogin()
syn <- synExtra::synDownloader("data")

wd <- here("clue_query")
dir.create(wd, showWarnings = FALSE)
```

## Goal

Query 



```{r loading}
# comp_res_raw <- syn("syn21559856") %>%
#   read_rds()

deseq_res <- syn("syn22028260") %>%
  read_rds()

signature_meta <- syn("syn21547101") %>%
  read_csv()

pertubation_meta <- syn("syn21547097") %>%
  read_csv()

cmap_gene_meta <- syn("syn21547102") %>%
  read_csv()

norm_drug <- function(x) {
  x %>%
    str_to_lower() %>%
    str_replace_all("[^a-zA-Z0-9]", "")
}

lspci_id_name_mapping <- synapser::synGet("syn22035396", version = 3) %>%
  chuck("path") %>%
  read_rds() %>%
  chuck("data", 2) %>%
  mutate(
    name_norm = norm_drug(name)
  ) %>%
  distinct()



```

```{r querying_cmap_dge}
ensembl <- useEnsembl(biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl", version = "98")

all_ensembl_ids <- deseq_res %>%
  pull(results) %>%
  map("ensembl_gene_id") %>%
  reduce(union)

gene_id_mapping <- getBM(
  c("entrezgene_id", "ensembl_gene_id"),
  filters = "ensembl_gene_id",
  values = all_ensembl_ids,
  mart = ensembl
)

unloadNamespace("biomaRt")
unloadNamespace("AnnotationDBI")

gene_id_mapping_valid <- gene_id_mapping %>%
  drop_na()

drug_id_lspci_id_mapping <- deseq_res %>%
  distinct(drug_id) %>%
  left_join(
    lspci_id_name_mapping %>%
      distinct(lspci_id, source_collapsed, name_norm),
    by = c("drug_id" = "name_norm")
  )
  

dge_gene_sets <- deseq_res %>%
  select(-samples, -design, -meta_deseq, -counts_deseq) %>%
  mutate(
    gene_sets = map(
      results,
      ~.x %>%
        inner_join(gene_id_mapping_valid, by = "ensembl_gene_id") %>%
        filter(padj < 0.1) %>%
        mutate(direction = if_else(log2FoldChange > 0, "up", "down")) %>%
        arrange(abs(log2FoldChange)) %>%
        group_nest(direction) %>%
        with(
          set_names(
            map(data, ~unique(.x[["entrezgene_id"]])),
            direction
          )
        )
    ),
    gene_set_name = lift(paste)(
      select(., -results) %>%
        as.list(),
      sep = "_"
    )
  )


MAX_PER_QUERY = 25
comp_res_clue <- dge_gene_sets %>%
  split(ceiling(seq_len(nrow(.)) / MAX_PER_QUERY)) %>%
  map(
    ~.x %>%
      select(-results) %>%
      unnest_longer(gene_sets, indices_to = "direction", values_to = "gene_id") %>%
      unchop(gene_id) %>%
      select(gene_set = gene_set_name, gene_id, direction)
  ) %>%
  map(
    clue_gmt_from_df,
    drop_invalid = TRUE
  )

comp_res_jobs <- comp_res_clue %>%
  imap(
    ~clue_query_submit(
      .x[["up"]], .x[["down"]],
      name = paste0("dge_job_", .y),
      use_fast_tool = TRUE
    )
  )

comp_res_jobs <- c(
  "5eb305a5d58eba0011f9031c",
  "5eb305a6ed2e4f0011539a5c",
  "5eb305a6d58eba0011f9031e",
  "5eb305a6ed2e4f0011539a5e",
  "5eb305a6d58eba0011f90320",
  "5eb305a7ed2e4f0011539a60"
)

failed_mask <- map(
  comp_res_jobs,
  clue_query_poll
) %>%
  map_lgl(~!identical(.x[["download_status"]], "completed"))

resub_jobs <- comp_res_clue[failed_mask] %>%
  imap(
    ~clue_query_submit(
      .x[["up"]], .x[["down"]],
      name = paste0("dge_job_", .y),
      use_fast_tool = FALSE
    )
  )

walk(
  comp_res_jobs,
  clue_query_wait
)

comp_res_clue_res <- map_chr(
  comp_res_jobs,
  clue_query_download
)

```

Put into synapse at syn21644366

```{r}
activity <- synapser::Activity(
  name = "Query clue",
  used = c(
    "syn21559859",
    "syn21547101",
    "syn21547097",
    "syn21547102"
  ),
  executed = "https://github.com/clemenshug/dge_comparison/blob/master/07_query_clue.Rmd"
)

c(
  comp_res_clue_res
) %>%
  synStoreMany(parentId = "syn21644366", activity = activity)


```


```{r pull_signatures}
cmap_paths <- list(
  GSE92742 = "syn21551046",
  GSE70138 = "syn21551043"
) %>%
  enframe("dataset", "synid") %>%
  mutate(
    path = map_chr(synid, syn),
    rids = map(
      path,
      read_gctx_ids, dim = "row"
    ),
    cids = map(
      path,
      read_gctx_ids, dim = "col"
    )
  )

signatures_dge <- signature_meta %>%
  distinct() %>%
  drop_na(lspci_id) %>%
  filter(lspci_id %in% deseq_res[["drug_id"]])

cmap_mats <- cmap_paths %>%
  mutate(
    mat = pmap(
      list(path, rids, cids),
      ~parse_gctx(..1, cid = which(..3 %in% signatures_dge[["sig_id"]]))
    )
  )

cmap_mat <- cmap_mats %>%
  pull(mat) %>%
  map(~.x@mat[order(rownames(.x@mat)), ]) %>%
  {do.call(cbind, .)}

cmap_df <- cmap_mat %>%
  as_tibble(rownames = "pr_gene_id") %>%
  mutate_at(vars(pr_gene_id), as.numeric) %>%
  inner_join(
    cmap_gene_meta %>%
      distinct(pr_gene_id, entrez_id),
    by = "pr_gene_id"
  ) %>%
  drop_na(entrez_id)

write_rds(
  cmap_df,
  file.path(wd, "cmap_signatures_profiled.rds"),
  compress = "gz"
)

cmap_df <- file.path(wd, "cmap_signatures_profiled.rds") %>%
  read_rds()
```


```{r querying_cmap_with_l1000}
# Take only highest concentration / longest time
selected_signatures <- signatures_dge %>%
  semi_join(
    arrange(., desc(pert_dose), desc(pert_time)) %>%
      group_by(lspci_id, pert_iname, cell_id) %>%
      slice(1) %>%
      ungroup(),
    by = c("lspci_id", "pert_iname", "cell_id", "pert_dose", "pert_time")
  )

zscores_selected_signatures <- cmap_df %>%
  select(entrez_id, one_of(selected_signatures[["sig_id"]])) %>%
  gather("sig_id", "zscore", -entrez_id) %>%
  inner_join(
    signatures_dge %>%
      select(sig_id, lspci_id, cell_id),
    by = "sig_id"
  )

# Aggregating multiple cells using procedure by 10.1016/j.cell.2017.10.049
zscores_selected_signatures_agg <- zscores_selected_signatures %>%
  as.data.table() %>%
  {
    # First aggregate replicates within same cell line
    .[
      ,
      .(zscore = mean(zscore)),
      keyby = c("entrez_id", "lspci_id", "cell_id")
    ][
      # Then across cell lines
      ,
      .(zscore_agg = quantile(zscore, c(0.67, 0.33), names = FALSE) %>%
        {.[order(abs(.))[2]]}
      ),
      by = c("entrez_id", "lspci_id")
    ]
  } %>%
  as_tibble()

# Using different quantile cutoffs for the z-score
selected_signatures_gene_sets <- tibble(
  cutoff = c(0.7, 0.8, 0.9, 0.95)
) %>%
  mutate(
    data = map(
      cutoff,
      ~zscores_selected_signatures_agg %>%
        filter(abs(zscore_agg) > qnorm(.x)) %>%
        arrange(desc(abs(zscore_agg))) %>%
        transmute(
          lspci_id,
          gene_id = as.character(entrez_id),
          direction = if_else(zscore_agg > 0, "up", "down"),
          gene_set = paste0(lspci_id, "_", .x)
        ) %>%
        {suppressWarnings(join_hgnc(., "gene_id", "entrez_id", "symbol"))}
    )
  ) %>%
  unnest(data) %>%
  group_nest(gene_set, lspci_id, cutoff)


MAX_PER_QUERY = 25
selected_signatures_gmts <- selected_signatures_gene_sets %>%
  # filter(gene_set == 1726) %>%
  # group_nest(gene_set) %>%
  filter(
    map_lgl(data, ~nrow(.) > 20)
  ) %>%
  split(ceiling(seq_len(nrow(.)) / MAX_PER_QUERY)) %>%
  map(
    ~bind_rows(set_names(.x[["data"]], .x[["gene_set"]]), .id = "gene_set") %>%
      select(gene_set, gene_id, direction)
  ) %>%
  map(
    clue_gmt_from_df,
    drop_invalid = TRUE
  )

selected_signatures_jobs <- selected_signatures_gmts %>%
  imap(
    ~clue_query_submit(
      .x[["up"]], .x[["down"]],
      name = paste0("l1000_job_", .y),
      use_fast_tool = FALSE
    )
  )

walk(
  selected_signatures_jobs,
  clue_query_wait
)

selected_signatures_dls <- selected_signatures_jobs %>%
  map_chr(clue_query_download)

activity <- synapser::Activity(
  name = "Query clue",
  used = c(
    "syn21559859",
    "syn21547101",
    "syn21547097",
    "syn21547102",
    "syn21551046",
    "syn21551043"
  ),
  executed = "https://github.com/clemenshug/dge_comparison/blob/master/07_query_clue.Rmd"
)

c(
  unname(selected_signatures_dls)
) %>%
  synStoreMany(parentId = "syn21644366", activity = activity)
```


```{r querying_cmap_with_l1000_measured_only}
# Take only highest concentration / longest time
selected_signatures <- signatures_dge %>%
  semi_join(
    arrange(., desc(pert_dose), desc(pert_time)) %>%
      group_by(lspci_id, pert_iname, cell_id) %>%
      slice(1) %>%
      ungroup(),
    by = c("lspci_id", "pert_iname", "cell_id", "pert_dose", "pert_time")
  )

zscores_selected_signatures <- cmap_df %>%
  filter(
    pr_gene_id %in% {
      filter(cmap_gene_meta, pr_is_lm == 1) %>% pull(pr_gene_id)
    }
  ) %>%
  select(entrez_id, one_of(selected_signatures[["sig_id"]])) %>%
  gather("sig_id", "zscore", -entrez_id) %>%
  inner_join(
    signatures_dge %>%
      select(sig_id, lspci_id, cell_id),
    by = "sig_id"
  )

# Aggregating multiple cells using procedure by 10.1016/j.cell.2017.10.049
zscores_selected_signatures_agg <- zscores_selected_signatures %>%
  as.data.table() %>%
  {
    # First aggregate replicates within same cell line
    .[
      ,
      .(zscore = mean(zscore)),
      keyby = c("entrez_id", "lspci_id", "cell_id")
    ][
      # Then across cell lines
      ,
      .(zscore_agg = quantile(zscore, c(0.67, 0.33), names = FALSE) %>%
        {.[order(abs(.))[2]]}
      ),
      by = c("entrez_id", "lspci_id")
    ]
  } %>%
  as_tibble()

selected_signatures_measured_only_gene_sets <- tibble(
  cutoff = c(0.7, 0.8, 0.9, 0.95)
) %>%
  mutate(
    data = map(
      cutoff,
      ~zscores_selected_signatures_agg %>%
        filter(abs(zscore_agg) > qnorm(.x)) %>%
        arrange(desc(abs(zscore_agg))) %>%
        transmute(
          lspci_id,
          gene_id = as.character(entrez_id),
          direction = if_else(zscore_agg > 0, "up", "down"),
          gene_set = paste0(lspci_id, "_", .x)
        ) %>%
        {suppressWarnings(join_hgnc(., "gene_id", "entrez_id", "symbol"))}
    )
  ) %>%
  unnest(data) %>%
  group_nest(gene_set, lspci_id, cutoff)


MAX_PER_QUERY <- 25
selected_signatures_gmts <- selected_signatures_measured_only_gene_sets %>%
  # filter(gene_set == 1726) %>%
  filter(
    map_lgl(data, ~nrow(.) > 20)
  ) %>%
  split(ceiling(seq_len(nrow(.)) / MAX_PER_QUERY)) %>%
  map(
    ~bind_rows(set_names(.x[["data"]], .x[["gene_set"]]), .id = "gene_set") %>%
      select(gene_set, gene_id, direction)
  ) %>%
  map(
    clue_gmt_from_df,
    drop_invalid = TRUE
  )

selected_signatures_jobs <- selected_signatures_gmts %>%
  imap(
    ~clue_query_submit(
      .x[["up"]], .x[["down"]],
      name = paste0("l1000_job_", .y),
      use_fast_tool = FALSE
    )
  )

walk(
  selected_signatures_jobs,
  clue_query_wait
)


selected_signatures_dls <- selected_signatures_jobs %>%
  map_chr(clue_query_download)

new_names <- file.path(dirname(selected_signatures_dls), paste0("l1000_query_measured_only_", 1:length(selected_signatures_dls), ".tar.gz"))

file.rename(
  selected_signatures_dls,
  new_names
)

activity <- synapser::Activity(
  name = "Query clue",
  used = c(
    "syn21559859",
    "syn21547101",
    "syn21547097",
    "syn21547102",
    "syn21551046",
    "syn21551043"
  ),
  executed = "https://github.com/clemenshug/dge_comparison/blob/master/07_query_clue.Rmd"
)

c(
  new_names
) %>%
  synStoreMany(parentId = "syn21644366", activity = activity)

```

Query using all signatures for Torin-1 seperately, not aggregating by cell line

```{r querying_cmap_with_l1000_single_cell_line}
# Take only highest concentration / longest time
selected_signatures <- signatures_dge %>%
  semi_join(
    arrange(., desc(pert_dose), desc(pert_time)) %>%
      group_by(lspci_id, pert_iname, cell_id) %>%
      slice(1) %>%
      ungroup(),
    by = c("lspci_id", "pert_iname", "cell_id", "pert_dose", "pert_time")
  ) %>%
  filter(pert_iname == "torin-1")

zscores_selected_signatures <- cmap_df %>%
  filter(
    pr_gene_id %in% {
      filter(cmap_gene_meta) %>% pull(pr_gene_id)
    }
  ) %>%
  select(entrez_id, one_of(selected_signatures[["sig_id"]])) %>%
  gather("sig_id", "zscore", -entrez_id) %>%
  inner_join(
    signatures_dge %>%
      select(sig_id, lspci_id, cell_id),
    by = "sig_id"
  )

# Aggregating multiple cells using procedure by 10.1016/j.cell.2017.10.049
zscores_selected_signatures_agg <- zscores_selected_signatures %>%
  as.data.table() %>%
  {
    # First aggregate replicates within same cell line
    .[
      ,
      .(zscore_agg = mean(zscore)),
      keyby = c("entrez_id", "lspci_id", "cell_id")
    ]
  } %>%
  as_tibble()

selected_signatures_per_cell_gene_sets <- tibble(
  cutoff = c(0.7, 0.8, 0.9, 0.95)
) %>%
  mutate(
    data = map(
      cutoff,
      ~zscores_selected_signatures_agg %>%
        filter(abs(zscore_agg) > qnorm(.x)) %>%
        arrange(desc(abs(zscore_agg))) %>%
        transmute(
          lspci_id,
          cell_id,
          gene_id = as.character(entrez_id),
          direction = if_else(zscore_agg > 0, "up", "down"),
          gene_set = paste0(lspci_id, "_", cell_id, "_", .x)
        ) %>%
        {suppressWarnings(join_hgnc(., "gene_id", "entrez_id", "symbol"))}
    )
  ) %>%
  unnest(data) %>%
  group_nest(gene_set, lspci_id, cell_id, cutoff)


MAX_PER_QUERY = 25
selected_signatures_gmts <- selected_signatures_per_cell_gene_sets %>%
  # filter(gene_set == 1726) %>%
  filter(
    map_lgl(data, ~nrow(.) > 20)
  ) %>%
  split(ceiling(seq_len(nrow(.)) / MAX_PER_QUERY)) %>%
  map(
    ~bind_rows(set_names(.x[["data"]], .x[["gene_set"]]), .id = "gene_set") %>%
      select(gene_set, gene_id, direction)
  ) %>%
  map(
    clue_gmt_from_df,
    drop_invalid = TRUE
  )

selected_signatures_jobs_by_cell <- selected_signatures_gmts %>%
  imap(
    ~clue_query_submit(
      .x[["up"]], .x[["down"]],
      name = paste0("l1000_job_", .y),
      use_fast_tool = FALSE
    )
  )

walk(
  selected_signatures_jobs_by_cell,
  clue_query_wait
)

selected_signatures_dls <- selected_signatures_jobs_by_cell %>%
  map_chr(clue_query_download)

new_names <- file.path(
  dirname(selected_signatures_dls), paste0("l1000_query_per_cell_line_", 1:length(selected_signatures_dls), ".tar.gz")
)

file.rename(
  selected_signatures_dls,
  new_names
)

activity <- synapser::Activity(
  name = "Query clue",
  used = c(
    "syn21559859",
    "syn21547101",
    "syn21547097",
    "syn21547102",
    "syn21551046",
    "syn21551043"
  ),
  executed = "https://github.com/clemenshug/dge_comparison/blob/master/07_query_clue.Rmd"
)

c(
  unname(new_names)
) %>%
  synStoreMany(parentId = "syn21644366", activity = activity)
```


```{r}
clue_res_raw <- synChildren("syn21644366") %>%
  map(syn) %>%
  keep(function(x) length(x) > 0)

# clue_res_raw %>%
#   magrittr::extract(str_starts(names(.), "my_")) %>%
#   map(synapser::synMove, new_parent = "syn22024427")

clue_res <- crossing(
  score_type = "tau",
  result_type = c("pert", "pcl"),
  score_level = c("cell", "summary")
) %>%
  mutate(
    data = pmap(
      .,
      function(...) {
        clue_res_raw %>%
          map(clue_parse_result, ...) %>%
          bind_rows(.id = "query_type") %>%
          mutate(
            query_type = case_when(
              str_detect(query_type, fixed("measured_only")) ~ "measured_only",
              str_detect(query_type, fixed("per_cell_line")) ~ "per_cell_line",
              TRUE ~ "aggregated"
            )
          )
      }
    )
  )

write_rds(
  clue_res,
  file.path(wd, "clue_results_conc.rds"),
  compress = "gz"
)
```


```{r synapse}
c(
  # file.path(wd, "cmap_signatures_profiled.rds"),
  file.path(wd, "clue_results_conc.rds")
) %>%
  synStoreMany(parentId = "syn21547022", activity = activity)
```


```{r save_gene_sets}
all_gene_sets <- tribble(
  ~source, ~query_type, ~data,
  "dge", NA_character_, rename(comp_res_gene_sets, data = result),
  "l1000", "aggregated", selected_signatures_gene_sets,
  "l1000", "per_cell_line", selected_signatures_per_cell_gene_sets,
  "l1000", "measured_only", selected_signatures_measured_only_gene_sets
) %>%
  mutate(
    data = map(
      data,
      ~.x %>%
        mutate_at(vars(data), map, ~select(.x, gene_id, symbol, direction))
    )
  ) %>%
  unnest(data) %>%
  select(source, query_type, gene_set, drug_id, lspci_id, cell_id, cutoff, data) %>%
  unnest(data)

write_csv(
  all_gene_sets,
  file.path(wd, "all_gene_sets.csv.gz")
)

activity <- synapser::Activity(
  name = "Query clue",
  used = c(
    "syn21559859",
    "syn21547101",
    "syn21547097",
    "syn21547102",
    "syn21551046",
    "syn21551043"
  ),
  executed = "https://github.com/clemenshug/dge_comparison/blob/master/07_query_clue.Rmd"
)

c(
  file.path(wd, "all_gene_sets.csv.gz")
) %>%
  synStoreMany(parentId = "syn21547022", activity = activity)

```

