---
title: "Clue connectivity analysis"
author: "Clemens Hug"
date: "4/1/2020"
output: html_document
---

```{r setup, include=FALSE}
library(synExtra)
library(tidyverse)
library(cmapR)
library(here)
library(egg)
library(broom)
library(ggrepel)

synapser::synLogin()
syn <- synExtra::synDownloader("data")

wd <- here("clue_query")
dir.create(wd, showWarnings = FALSE)

theme_set(theme_bw())
```


```{r load}
compound_name_map <- synapser::synGet("syn22035396", version = 3) %>%
  chuck("path") %>%
  read_rds() %>%
  filter(fp_name == "morgan_normal") %>%
  chuck("data", 1) %>%
  distinct(
    lspci_id,
    name = str_to_lower(name)
  )

cmap_signatures_profiled <- syn("syn21747571") %>%
  read_rds()

cmap_gene_meta <- syn("syn21547102") %>%
  read_csv()

clue_res_dge <- syn("syn21907139") %>%
  read_rds()

clue_res_l1000 <- syn("syn21907143") %>%
  read_rds()

clue_res_combined <- syn("syn21907166") %>%
  read_rds()

diff_exp_by_conc <- syn("syn21559856") %>%
  read_rds()

diff_exp_linear <- syn("syn21559859") %>%
  read_rds()

pertubation_meta <- syn("syn21547097") %>%
  read_csv()

signature_meta <- syn("syn21547101") %>%
  read_csv()

```



```{r connectivity_plots}
self_conn_plot <- function(df, label = pert_iname) {
  label_q <- enquo(label)
  df %>%
    ggplot(aes(x = 0, y = tau)) +
    # geom_segment(
    #   aes(yend = normalized_score),
    #   xend = 0.2
    # ) +
    geom_point(
      color = "red"
    ) +
    geom_text_repel(
      aes(label = !!label_q),
      x = 0.05,
      nudge_x = 1,
      hjust = 1,
      segment.color = "gray50"
    ) +
    theme_minimal() +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      axis.title.x = element_blank()
    ) +
    coord_cartesian(xlim = c(0, 1)) +
    labs(y = "CMap connectivity score", title = "Self-connectivity CMap")
}

# Query using DGE, taking best matching target cell line
cmap_match_all_summary <- clue_res_dge %>%
  filter(score_level == "summary", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_target == lspci_id_query) %>%
  arrange(desc(tau)) %>%
  group_by(lspci_id_query) %>%
  slice(1) %>%
  ungroup() %>%
  self_conn_plot() +
  labs(title = "Self-connectivity cells merged")

ggsave(
  file.path(wd, "cmap_match_all_summary.pdf"),
  cmap_match_all_summary,
  width = 3, height = 10
)

# Query using DGE, taking only matching cell line
cmap_match_cell_cell <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_target == lspci_id_query, cell_id_target == cell_id_query) %>%
  arrange(desc(tau)) %>%
  group_by(lspci_id_query) %>%
  slice(1) %>%
  ungroup() %>%
  self_conn_plot() +
  labs(title = "Self-connectivity cells matched")

ggsave(
  file.path(wd, "cmap_match_cell_cell.pdf"),
  cmap_match_cell_cell,
  width = 3, height = 10
)

# Query using DGE, taking best matching target cell line
cmap_match_cell_best_matching <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_target == lspci_id_query) %>%
  arrange(desc(tau)) %>%
  group_by(lspci_id_query) %>%
  slice(1) %>%
  ungroup() %>%
  self_conn_plot() +
  labs(title = "Self-connectivity best matching cell")

ggsave(
  file.path(wd, "cmap_match_cell_best_matching.pdf"),
  cmap_match_cell_best_matching,
  width = 3, height = 10
)

cmap_match_cell_worst_matching <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_target == lspci_id_query) %>%
  arrange(tau) %>%
  group_by(lspci_id_query) %>%
  slice(1) %>%
  ungroup() %>%
  self_conn_plot() +
  labs(title = "Self-connectivity worst matching cell")

ggsave(
  file.path(wd, "cmap_match_cell_worst_matching.pdf"),
  cmap_match_cell_worst_matching,
  width = 3, height = 10
)

clue_match_best_vs_worst <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_target == lspci_id_query) %>%
  arrange(tau) %>%
  group_by(lspci_id_query) %>%
  # Make sure that drugs have been profiled in adequate number of cell lines
  filter(n() >= 4) %>%
  slice(c(1, n())) %>%
  mutate(match = factor(c("worst", "best"), levels = c("best", "worst", ""))) %>%
  ungroup() %>%
  ggplot(aes(match, tau, group = lspci_id_query)) +
  geom_line() +
  labs(x = "CMap cell line match", y = "Connectivity score") +
  scale_x_discrete(drop = FALSE) +
  geom_text_repel(
    aes(label = pert_iname, x = "worst"),
    data = ~.x %>%
      filter(match == "worst"),
    nudge_x = 2,
    hjust = 1,
    segment.color = "gray50"
  ) +
  geom_point(
    color = "red"
  ) +
  labs(title = "Self-connectivity best and worst matching cell")

ggsave(
  file.path(wd, "clue_match_best_vs_worst.pdf"),
  clue_match_best_vs_worst,
  width = 5, height = 10
)

```


```{r top_per_drug}

top_hit_plot <- function(df, label = "pert_iname") {
  label_q <- sym(label)
  ggplot(df, aes(x = 0, y = tau)) +
    geom_text_repel(
      aes(y = tau, label = !!label_q),
      hjust = 1,
      nudge_x = rep_len(nrow(df), 1),
      nudge_y = df$tau_rescaled - df$tau,
      force = 0,
      segment.color = "gray50"
    ) +
    geom_point(
      color = "red"
    ) +
    theme_minimal() +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank(),
      axis.title.x = element_blank()
    ) +
    coord_cartesian(xlim = c(0, 1)) +
    labs(y = "CMap connectivity score")
}

find_draw_top_hits <- function(
  df,
  n_top = 10,
  ...,
  plot_args = list()
) {
  dots <- list(...)
  filter_args <- dots %>%
    magrittr::extract(intersect(colnames(df), names(.)))
  plot_data <- df %>%
    filter(
      imap(., ~if (.y %in% names(filter_args)) .x %in% filter_args[[.y]] else TRUE) %>%
        reduce(magrittr::and)
    ) %>%
    group_by(pert_id) %>%
    arrange(desc(tau), .by_group = TRUE) %>%
    slice(1) %>%
    ungroup() %>%
    arrange(desc(tau)) %>%
    slice(seq_len(n_top)) %>%
    mutate(tau_rescaled = scales::rescale(-seq_len(n()), to = c(min(tau), max(tau))))
  exec(top_hit_plot, plot_data, !!!plot_args) +
    labs(title = paste0("Top ", n_top, " hits"))
}

palbo_plot <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "palbociclib")$lspci_id,
    plot_args = list(label = "pert_iname")
  )

alvo_plot <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "alvocidib")$lspci_id,
    plot_args = list(label = "pert_iname")
  )

alvo_plot_l1000 <- clue_res_l1000 %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "alvocidib")$lspci_id,
    plot_args = list(label = "pert_iname")
  )

top_hit_comp_plot <- function(df, label = "pert_iname") {
  label_q <- sym(label)
  label_data <- df %>%
    filter(source == tail(levels(source), 1)) %>%
    mutate(tau_rescaled = scales::rescale(-seq_len(n()), to = c(min(df[["tau"]]), max(df[["tau"]]))))
  n_sources <- length(levels(df[["source"]]))
  df %>%
    ggplot(aes(x = source, y = tau)) +
    geom_line(
      aes(group = pert_id)
    ) +
    theme_minimal() +
    geom_text_repel(
      aes(x = n_sources, y = tau, label = !!label_q),
      data = label_data,
      hjust = 1,
      nudge_x = rep_len(nrow(label_data), n_sources + 2),
      nudge_y = label_data$tau_rescaled - label_data$tau,
      force = 0,
      segment.color = "gray50"
    ) +
    geom_point(
      color = "red"
    ) +
    # theme(
    #   panel.grid.major.x = element_blank(),
    #   panel.grid.minor.x = element_blank(),
    #   axis.ticks.x = element_blank(),
    #   axis.text.x = element_blank(),
    #   axis.title.x = element_blank()
    # ) +
    coord_cartesian(xlim = c(0.5, n_sources + 3),  expand = FALSE) +
    labs(y = "CMap connectivity score")
}


find_draw_top_hit_comps <- function(
  df,
  n_top = 10,
  ...,
  plot_args = list()
) {
  dots <- list(...)
  filter_args <- dots %>%
    magrittr::extract(intersect(colnames(df), names(.)))
  sources <- unique(df[["source"]])
  plot_data <- df %>%
    mutate(source = factor(source, levels = sources)) %>%
    filter(
      imap(., ~if (.y %in% names(filter_args)) .x %in% filter_args[[.y]] else TRUE) %>%
        reduce(magrittr::and)
    ) %>%
    group_by(pert_id, source) %>%
    arrange(desc(tau), .by_group = TRUE) %>%
    slice(1) %>%
    ungroup() %>%
    filter(
      pert_id %in% (
        group_by(., source) %>%
          arrange(desc(tau), .by_group = TRUE) %>%
          slice(seq_len(n_top)) %>%
          ungroup() %>%
          pull(pert_id)
      )
    )
  exec(top_hit_comp_plot, plot_data, !!!plot_args) +
    labs(title = paste0("Top ", n_top, " hits"))
}

top_hits_both_alvocidib <- clue_res_combined %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hit_comps(
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "alvocidib")$lspci_id,
    n_top = 20
  ) +
  labs(title = "Top 20 hits for Alvocidib")

top_hits_both_alvocidib <- clue_res_combined %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  filter(lspci_id_query == 21311, lspci_id_target == 21311)


ggsave(
  file.path(wd, "clue_match_alvocidib_dge_vs_l1000.pdf"),
  top_hits_both_alvocidib,
  width = 5, height = 10
)

top_hits_both_alvocidib_pcl <- clue_res_combined %>%
  filter(score_level == "cell", result_type == "pcl") %>%
  chuck("data", 1) %>%
  find_draw_top_hit_comps(
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "alvocidib")$lspci_id,
    n_top = 20,
    plot_args = list(label = "pert_id")
  ) +
  labs(title = "Top 20 hits for Alvocidib")

ggsave(
  file.path(wd, "clue_match_alvocidib_dge_vs_l1000_pcl.pdf"),
  top_hits_both_alvocidib_pcl,
  width = 8, height = 10
)
```



```{r drugs_not_cmap}
drugs_dge <- diff_exp_by_conc %>%
  pull(lspci_id) %>%
  unique()

pertubation_meta

drugs_dge_not_cmap <- diff_exp_by_conc %>%
  filter(lspci_id %in% drugs_dge[!drugs_dge %in% pertubation_meta$lspci_id]) %>%
  select_if(negate(is.list))

ribo_top_hits <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "ribociclib")$lspci_id,
    plot_args = list(label = "pert_iname")
  ) +
  labs(title = "Top 30 hits for Ribociclib (DGE)")

ggsave(
  file.path(wd, "clue_match_ribociclib.pdf"),
  ribo_top_hits,
  width = 5, height = 10
)

ribo_top_pcl <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pcl") %>%
  chuck("data", 1) %>%
  filter(str_starts(pert_id, fixed("CP"))) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "ribociclib")$lspci_id,
    plot_args = list(label = "pert_id")
  ) +
  labs(title = "Top 30 hits for Ribociclib (DGE)")

ggsave(
  file.path(wd, "clue_match_ribociclib_pcl.pdf"),
  ribo_top_pcl,
  width = 5, height = 10
)

xl019_top_hits <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pert") %>%
  chuck("data", 1) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "xl019")$lspci_id,
    plot_args = list(label = "pert_iname")
  ) +
  labs(title = "Top 30 hits for XL019 (DGE)")

ggsave(
  file.path(wd, "clue_match_xl019.pdf"),
  xl019_top_hits,
  width = 5, height = 10
)

xl019_top_pcl <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pcl") %>%
  chuck("data", 1) %>%
  filter(str_starts(pert_id, fixed("CP"))) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "xl019")$lspci_id,
    plot_args = list(label = "pert_id")
  ) +
  labs(title = "Top 30 hits for XL1019 (DGE)")

ggsave(
  file.path(wd, "clue_match_xl019_pcl.pdf"),
  xl019_top_pcl,
  width = 5, height = 10
)

vlx1570_top_pcl <- clue_res_dge %>%
  filter(score_level == "cell", result_type == "pcl") %>%
  chuck("data", 1) %>%
  filter(str_starts(pert_id, fixed("CP"))) %>%
  find_draw_top_hits(
    n_top = 30,
    pert_type = "trt_cp",
    lspci_id_query = filter(compound_name_map, name == "vlx1570")$lspci_id,
    plot_args = list(label = "pert_id")
  ) +
  labs(title = "Top 30 hits for VLX1570 (DGE)")

ggsave(
  file.path(wd, "clue_match_vlx1570_pcl.pdf"),
  vlx1570_top_pcl,
  width = 5, height = 10
)

```

```{r dose_response}

ensembl_hugo_map <- diff_exp_by_conc %>%
  pull("result") %>%
  map("ensembl_gene_id") %>%
  reduce(union) %>%
  genebabel::query_hgnc("ensembl_gene_id")

etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
theme_bold <- function() {
    theme(axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
          axis.text.y = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          title = etxt(12))
}

calculate_dose_response_l1000 <- function(meta, signatures, z_threshold = 1.645) {
  select_signatures <- signatures %>%
    select(pr_gene_id, one_of(meta[["sig_id"]])) %>%
    filter(
      select(., -pr_gene_id) %>%
        mutate_all(~abs(.x) >= z_threshold) %>%
        purrr::reduce(magrittr::or)
    )
  select_signatures %>%
    gather("sig_id", "z_score", -pr_gene_id) %>%
    inner_join(
      select(meta, sig_id, pert_dose), by = "sig_id"
    ) %>%
    mutate(change_norm = z_score) %>%
    rename(change = z_score, drug_conc = pert_dose) %>%
    group_nest(pr_gene_id)
}

calculate_dose_response_dge <- function(data, p_threshold = 0.05) {
  selected_signatures <- data %>%
    select(condition, result) %>%
    unnest(result) %>%
    # mutate(log2FoldChange = log2FoldChange_MLE) %>%
    group_by(condition) %>%
    mutate(change_norm = scale(log2FoldChange)) %>%
    ungroup() %>%
    group_by(ensembl_gene_id) %>%
    filter(any(na.omit(padj) <= p_threshold)) %>%
    ungroup() %>%
    select(condition, ensembl_gene_id, log2FoldChange, change_norm)
  selected_signatures %>%
    inner_join(
      select(data, condition, drug_conc), by = "condition"
    ) %>%
    rename(change = log2FoldChange) %>%
    drop_na(change) %>%
    group_nest(ensembl_gene_id)
}

calculate_dose_response <- function(drug, cell, time, p_threshold = 0.05, method = "spearman", round_digits = 1) {
  # browser()
  l1000 <- signature_meta %>%
    distinct() %>%
    filter(lspci_id == drug, cell_id == cell, if (!is.null(time)) pert_time == time else TRUE) %>%
    select_if(negate(is.list)) %>%
    calculate_dose_response_l1000(cmap_signatures_profiled, z_threshold = qnorm(1 - p_threshold)) %>%
    inner_join(cmap_gene_meta %>% filter(pr_is_lm == 1) %>% select(pr_gene_id, symbol), by = "pr_gene_id")
  dge <- diff_exp_by_conc %>%
    filter(lspci_id == !!drug, cells == cell, if (!is.null(time)) replace_na(time == !!time, TRUE) else TRUE) %>%
    calculate_dose_response_dge(p_threshold = p_threshold) %>%
    inner_join(select(ensembl_hugo_map, ensembl_gene_id, symbol), by = "ensembl_gene_id")
  list(
    l1000 = l1000,
    dge = dge
  ) %>%
    bind_rows(.id = "method") %>%
    mutate(
      test = map(
        data,
        ~suppressWarnings(cor.test(
          if (round_digits > 0) round(.x[["change"]], digits = round_digits) else x[["change"]],
          .x[["drug_conc"]], method = !!method
        ))
      )
    ) %>%
    group_by(symbol) %>%
    filter(length(unique(method)) == 2, n() == 2) %>%
    ungroup() %>%
    select(symbol, method, test, data)
}

dose_response_pairwise <- function(df) {
  df %>%
    select(symbol, method, test) %>%
    spread(method, test) %>%
    mutate(
      significance = select(., dge, l1000) %>%
        mutate_all(map_lgl, ~.x[["p.value"]] < 0.05) %>%
        {
          case_when(
            .[["dge"]] & .[["l1000"]] ~ "both",
            .[["dge"]] ~ "dge_only",
            .[["l1000"]] ~ "l1000_only",
            TRUE ~ "neither"
          )
        }
    ) %>%
    mutate_at(vars(dge, l1000), map_dbl, "estimate")
}

dose_response_pairwise_fisher <- function(df) {
  tab <- df %>%
    select(dge, l1000) %>%
    gather("method", "correlation") %>%
    mutate_at(vars(correlation), ~if_else(abs(.x) > 0.25, "correlated", "uncorrelated")) %>%
    table()
  test <- fisher.test(tab, conf.int = TRUE,conf.level = .95)
  list(tab, test)
}

dose_response_curve <- function(df) {
  scale_factor <- df %>%
    group_by(method) %>%
    summarize(max_val = max(abs(change))) %>%
    ungroup() %>%
    spread(method, max_val) %>%
    {.[["l1000"]]/.[["dge"]]}
  df %>%
    mutate(
      change_scaled = if_else(method == "dge", change*scale_factor, change)
    ) %>%
    # ggplot(aes(drug_conc, change_norm, color = method)) +
    ggplot(aes(drug_conc, change_scaled, color = method)) +
    geom_hline(yintercept = 0, color = "grey30") +
    geom_point(alpha = 0.5) +
    scale_y_continuous(
      sec.axis = sec_axis(~./scale_factor, name = "DGE")
    ) +
    geom_smooth(aes(fill = method, group = method), method = "lm", alpha = 0.2) +
    scale_x_log10() +
    labs(x = "Dose (uM)", y = "L1000")
}

dose_response_cor_and_curves <- function(df, seed = 42, highlighted_genes = NULL) {
  set.seed(seed)
  dose_cor_plot_data <- dose_response_pairwise(df) %>%
    mutate(
      pos = case_when(
        dge < 0.25 & abs(l1000) < 0.25 ~ "left_middle",
        dge < 0.25 & l1000 < 0.25 ~ "left_bottom",
        dge > 0.25 & abs(l1000) < 0.25 ~ "right_middle",
        dge > 0.25 & l1000 > 0.25 ~ "right_top",
        TRUE ~ "no"
      )
    ) %>%
    group_by(pos) %>%
    mutate(
      selected = if (unique(pos) == "no")
        "no"
      else if (!is.null(highlighted_genes))
        if_else(symbol %in% highlighted_genes, pos, "no")
      else
        sample(c(rep_len("no", n() - 1), unique(pos)), n())
    ) %>%
    ungroup()
  dose_fisher <- dose_response_pairwise_fisher(dose_cor_plot_data)
  cor_plot <- dose_cor_plot_data %>%
    mutate(
      color_selected = if_else(selected == "no", "black", "red") %>%
        factor(levels = c("black", "red"))
    ) %>%
    arrange(color_selected) %>%
    ggplot(aes(dge, l1000, color = color_selected)) +
    geom_hline(yintercept = c(-0.25, 0.25), color = "grey30") +
    geom_vline(xintercept = c(-0.25, 0.25), color = "grey30") +
    annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "yellow", alpha = 0.2)),
      xmin = -1, xmax = -0.25, ymin = -1, ymax = -0.25
    ) +
    annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "yellow", alpha = 0.2)),
      xmin = 0.25, xmax = 1, ymin = 0.25, ymax = 1
    ) +
    annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "magenta", alpha = 0.2)),
      xmin = -0.25, xmax = 0.25, ymin = 0.25, ymax = 1
    ) +
    annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "magenta", alpha = 0.2)),
      xmin = -0.25, xmax = 0.25, ymin = -1, ymax = -0.25
    ) +
      annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "cyan", alpha = 0.2)),
      xmin = -1, xmax = -0.25, ymin = -0.25, ymax = 0.25
    ) +
    annotation_custom(
      grid::rectGrob(gp = grid::gpar(fill = "cyan", alpha = 0.2)),
      xmin = 0.25, xmax = 1, ymin = -0.25, ymax = 0.25
    ) +
    coord_cartesian(expand = FALSE) +
    geom_point(aes(size = selected), alpha = 0.8) +
    scale_size_manual(
      values = c("no" = 2, "left_middle" = 3, "left_bottom" = 3, "right_middle" = 3, "right_top" = 3),
      guide = FALSE
    ) +
    geom_text_repel(
      aes(label = symbol),
      data = ~.x %>%
        mutate(symbol = if_else(selected == "no", "", symbol)),
      # box.padding = 0.5,
      # point.padding = 0.5,
      max.iter = 8000
    ) +
    coord_equal(xlim = c(-1, 1), ylim = c(-1, 1)) +
    scale_color_identity() +
    guides(color = FALSE) +
    labs(x = "Dose-response correlation DGE", y = "Dose-respose correlation L1000")
  dose_plots <- df %>%
    inner_join(
      dose_cor_plot_data %>%
        filter(selected != "no"),
      by = "symbol"
    ) %>%
    select(symbol, pos, method, data) %>%
    unnest(data) %>%
    group_nest(symbol, pos) %>%
    mutate(
      plot = map(data, dose_response_curve) %>%
        map2(symbol, ~.x + labs(title = .y))
    ) %>%
    {set_names(.[["plot"]], .[["pos"]])}
  arrangeGrob(
    grobs = list(
      cor_plot +
        labs(title = "Palbociclib dose-response correlation"),
      dose_plots[["left_middle"]] +
        theme(legend.position = "none"),
      dose_plots[["left_bottom"]] +
        theme(legend.position = "none"),
      dose_plots[["right_middle"]],
      dose_plots[["right_top"]]
    ) %>%
      map(~.x + theme_bold()) %>%
      c(
        list(
          grid::nullGrob(),
          grid::nullGrob()
        )
      ),
    layout_matrix = rbind(
      c(2, 6, 1, 7, 5),
      c(3, 6, 1, 7, 4)
    ),
    widths = unit(c(4, 0.1, 6, 0.1, 5), "in"),
    heights = unit(c(3, 3), "in")
  )
}


palbo_dose_cor <- calculate_dose_response(
  filter(compound_name_map, name == "palbociclib")$lspci_id,
  "MCF7", time = 24
)

picked_genes <- c(
  "FAM20B", "VPS28", "EGR1", "HPRT1"
)

palbo_dose_cor_plot <- dose_response_cor_and_curves(
  palbo_dose_cor, seed = 1, highlighted_genes = picked_genes
)

grid::grid.draw(palbo_dose_cor_plot)

ggsave(
  file.path(wd, "palbo_dose_cor_plot.png"),
  palbo_dose_cor_plot, width = 15.5, height = 6
)

palbo_dose_cor_plot_data <- dose_response_pairwise(palbo_dose_cor)

palbo_dose_fisher <- dose_response_pairwise_fisher(palbo_dose_cor_plot_data)

palbo_dose_cor_plot <- palbo_dose_cor_plot_data %>%
  ggplot(aes(dge, l1000)) +
  geom_hline(yintercept = c(-0.25, 0.25), color = "grey30") +
  geom_vline(xintercept = c(-0.25, 0.25), color = "grey30") +
  geom_point(alpha = 0.8) +
  coord_equal(xlim = c(-1, 1), ylim = c(-1, 1)) +
  labs(title = "Palbociclib dose-response correlation per gene")

ggsave(
  file.path(wd, "palbo_dose_cor_plot_significance.pdf"),
  palbo_dose_cor_plot,
  width = 6, height = 5
)


palbo_dose_srsf3 <- palbo_dose_cor %>%
  select(symbol, method, data) %>%
  filter(symbol == "SRSF3") %>%
  unnest(data) %>%
  dose_response_curve()

ggsave(
  file.path(wd, "palbo_dose_srsf3.pdf"),
  palbo_dose_srsf3,
  width = 6, height = 4
)
```

