---
title: "Investigate novel drugs"
output: html_notebook
---

```{r setup, include=FALSE}
library(synExtra)
library(tidyverse)
library(cmapR)
library(here)
library(egg)
library(broom)
library(ggrepel)
library(seriation)

synapser::synLogin()
syn <- synExtra::synDownloader("data")

wd <- here("clue_query")
dir.create(wd, showWarnings = FALSE)

theme_set(theme_bw())
```




```{r load}
compound_name_map <- syn("syn22035396.3") %>%
  read_rds() %>%
  filter(fp_name == "morgan_normal") %>%
  chuck("data", 1)

cmap_gene_meta <- syn("syn21547102") %>%
  read_csv()

clue_res_dge <- syn("syn21907139") %>%
  read_rds()

clue_res_l1000 <- syn("syn21907143") %>%
  read_rds()

clue_res_combined <- syn("syn21907166.4") %>%
  read_rds()
# clue_res_combined_2 <- clue_res_combined

pertubation_meta <- syn("syn21547097.6") %>%
  read_csv()

signature_meta <- syn("syn21547101.6") %>%
  read_csv()

dge_meta <- syn("syn22000707.8") %>%
  read_rds()

deseq_res <- syn("syn22017733.1") %>%
  read_rds()

deseq_meta <- syn("syn21558154.4") %>%
  read_rds()

```

```{r find_gene_sets}
# Find gene sets that are actuallly used
# No stimulus, last available time point

meta_long <- syn("syn22000707.11") %>%
  read_rds() %>%
  unnest(meta)

used_dge_signatures <- meta_long %>%
  filter(is.na(stim) | stim == "control", dataset != "fp_transdiff") %>%
  distinct(dataset, date, cells, drug, time) %>%
  group_by(dataset, date, cells, drug) %>%
  arrange(desc(time)) %>%
  slice_head(n = 1) %>%
  ungroup()
  
cdk_used_dge_signatures <- used_dge_signatures %>%
  filter(dataset == "lincs_cdk4_6_7")

write_csv(
  cdk_used_dge_signatures,
  "cdk_used_signatures.csv"
)

```


```{r sr_drug_repurposing}
## Load all results
R <- clue_res_combined %>%
    filter( result_type == "pcl", score_level == "summary" ) %>%
    pluck( "data", 1 )

## Identify relevant gene sets
dubs <- deseq_res %>%
  mutate(
    gene_set = condition_conc %>%
      str_replace_all("\\s", "_") %>%
      str_replace_all("[^\\w]", "")
  ) %>%
  semi_join(
    dge_meta %>%
        unnest(meta) %>%
        filter(dataset == "sr_repurposing", !lspci_id %in% signature_meta$lspci_id, is.na(stim)) %>%
        group_by(drug_id) %>%
        arrange(desc(time)) %>%
        slice(1),
    by = c("cells", "drug_id", "time", "stim")
  )

x <- compound_name_map %>%
  group_by(lspci_id) %>%
  slice(1) %>%
  ungroup() %>%
  select(lspci_id, name)

## Isolate the appropriate slice of data
## Aggregate across multiple entries to compute master similarity score
R2 <- R %>%
  drop_na(tau) %>%
  # filter(pert_type == "trt_cp") %>%
  inner_join(
    dubs %>%
      distinct(gene_set, drug_id),
    by = "gene_set"
  ) %>%
  rename(pert_iname = id) %>%
  # inner_join(
  #   x,
  #   by = c("lspci_id_query" = "lspci_id")
  # ) %>%
  group_by( pert_iname, name_query, source, z_score_cutoff ) %>%
  summarize_at( "tau", ~.x[ which.max(abs(.x)) ] ) %>%
  ungroup() %>%
  mutate_at( "source", toupper )

# FInd most similar drugs per query

R3 <- R2 %>%
  filter(
    pert_iname %in% {
      group_by(., name_query) %>%
        arrange(desc(tau), .by_group = TRUE) %>%
        slice(1:5) %>%
        ungroup() %>%
        pull(pert_iname)
    }
  )

## Perform hierarchical clustering on drugT profiles (columns in the final plot)
## Use the DGE slice because it is cleaner and less saturated
DM <- R3 %>% filter( source == "DGE" ) %>% select( name_query, pert_iname, tau ) %>%
    spread( name_query, tau ) %>% as.data.frame %>% column_to_rownames("pert_iname")
comp_order <- function(m) {
  dm <- dist(m)
  hclust(dm) %>% reorder(dm) %>%  dendextend::order.hclust() %>% labels(dm)[.]
}
lvl <- comp_order(DM)
lvl2 <- comp_order(t(DM))

## Fix the order via factor levels
R3 <- R3 %>% mutate(name_query = factor(name_query, lvl2),
                    pert_iname = factor(pert_iname, lvl))

# # Complete missing observations at z-scores that yielded insufficient
# # genes for Clue with NA
# R2_completed <- bind_rows(
#     R2 %>%
#         filter(source == "DGE"),
#     R2 %>%
#         filter(source == "L1000") %>%
#         complete(nesting(idQ, idT, source, drugT, drugQ), z_score_cutoff)
# )

## Plotting elements
pal <- rev(RColorBrewer::brewer.pal(n=7, name="RdBu"))
etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
theme_bold <- function() {
    theme(axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
          axis.text.y = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          axis.ticks = element_blank())
}

## Plotting a heatmap of clue hits
fplot <- function(X) {
    ggplot( X, aes(x=name_query, y=pert_iname, fill=tau) ) +
        theme_minimal() + theme_bold() +
        geom_tile(color="black") +
        # geom_tile(data=filter(X, idQ==idT), color="black", size=1) +
        scale_fill_gradientn( colors=pal, limits=c(-100,100) ) +
        labs(x = "Drug query", y = "Clue target class", fill = "Tau" )
}

ggsave(
  file.path(wd, "sr_repurposing_unknown_drugs_pcl.png"),
  fplot(R3),
  width = 8, height = 10
)
```

```{r dubs}


## Identify relevant gene sets
dubs <- deseq_res %>%
  mutate(
    gene_set = condition_conc %>%
      str_replace_all("\\s", "_") %>%
      str_replace_all("[^\\w]", "")
  ) %>%
  semi_join(
    dge_meta %>%
        unnest(meta) %>%
        filter(dataset == "ld_dub", !lspci_id %in% signature_meta$lspci_id, is.na(stim)) %>%
        group_by(drug_id) %>%
        arrange(desc(time)) %>%
        slice(1),
    by = c("cells", "drug_id", "time", "stim")
  )

## Isolate the appropriate slice of data
## Aggregate across multiple entries to compute master similarity score
R2 <- R %>%
  drop_na(tau) %>%
  # filter(pert_type == "trt_cp") %>%
  inner_join(
    dubs %>%
      distinct(gene_set, drug_id),
    by = "gene_set"
  ) %>%
  dplyr::rename(pert_iname = id) %>%
  group_by( pert_iname, name_query, source, z_score_cutoff ) %>%
  summarize_at( "tau", ~.x[ which.max(abs(.x)) ] ) %>%
  ungroup() %>%
  mutate_at( "source", toupper )

# FInd most similar drugs per query

R3 <- R2 %>%
  dplyr::filter(
    pert_iname %in% {
      group_by(R2, name_query) %>%
        arrange(desc(tau), .by_group = TRUE) %>%
        slice(1:5) %>%
        ungroup() %>%
        pull(pert_iname)
    }
  )


## Perform hierarchical clustering on drugT profiles (columns in the final plot)
## Use the DGE slice because it is cleaner and less saturated
DM <- R3 %>% filter( source == "DGE" ) %>% select( name_query, pert_iname, tau ) %>%
    spread( name_query, tau ) %>% as.data.frame %>% column_to_rownames("pert_iname")
comp_order <- function(m) {
  dm <- dist(m)
  hclust(dm) %>% reorder(dm) %>%  dendextend::order.hclust() %>% labels(dm)[.]
}
lvl <- comp_order(DM)
lvl2 <- comp_order(t(DM))

## Fix the order via factor levels
R3 <- R3 %>% mutate(name_query = factor(name_query, lvl2),
                    pert_iname = factor(pert_iname, lvl))

# # Complete missing observations at z-scores that yielded insufficient
# # genes for Clue with NA
# R2_completed <- bind_rows(
#     R2 %>%
#         filter(source == "DGE"),
#     R2 %>%
#         filter(source == "L1000") %>%
#         complete(nesting(idQ, idT, source, drugT, drugQ), z_score_cutoff)
# )

## Plotting elements
pal <- rev(RColorBrewer::brewer.pal(n=7, name="RdBu"))
etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
theme_bold <- function() {
    theme(axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
          axis.text.y = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          axis.ticks = element_blank())
}

## Plotting a heatmap of clue hits
fplot <- function(X) {
    ggplot( X, aes(x=name_query, y=pert_iname, fill=tau) ) +
        theme_minimal() + theme_bold() +
        geom_tile(color="black") +
        # geom_tile(data=filter(X, idQ==idT), color="black", size=1) +
        scale_fill_gradientn( colors=pal, limits=c(-100,100) ) +
        labs(x = "Drug query", y = "Clue target class", fill = "Tau" )
}

ggsave(
  file.path(wd, "sr_repurposing_unknown_drugs_pcl.png"),
  fplot(R3),
  width = 8, height = 10
)
```


```{r combined_heatmaps}


## Identify relevant gene sets
dubs <- deseq_res %>%
  mutate(
    gene_set = condition_conc %>%
      str_replace_all("\\s", "_") %>%
      str_replace_all("[^\\w]", "")
  ) %>%
  inner_join(
    dge_meta %>%
        unnest(meta) %>%
        filter(
          dataset %in% c("sr_repurposing", "ld_dub"),
          !lspci_id %in% signature_meta$lspci_id, is.na(stim)
        ) %>%
        group_by(drug_id) %>%
        arrange(desc(time)) %>%
        slice(1) %>%
        select(cells, drug_id, time, stim, dataset),
    by = c("cells", "drug_id", "time", "stim")
  )

## Isolate the appropriate slice of data
## Aggregate across multiple entries to compute master similarity score
R2 <- R %>%
  drop_na(tau) %>%
  # filter(pert_type == "trt_cp") %>%
  inner_join(
    dubs %>%
      distinct(gene_set, drug_id, dataset),
    by = "gene_set"
  ) %>%
  dplyr::rename(pert_iname = id) %>%
  group_by( pert_iname, name_query, source, z_score_cutoff, dataset ) %>%
  summarize_at( "tau", ~.x[ which.max(abs(.x)) ] ) %>%
  ungroup() %>%
  mutate_at( "source", toupper )

# FInd most similar drugs per query

R3 <- R2 %>%
  dplyr::filter(
    pert_iname %in% {
      group_by(R2, name_query) %>%
        arrange(desc(tau), .by_group = TRUE) %>%
        slice(1:5) %>%
        ungroup() %>%
        pull(pert_iname)
    }
  )


## Perform hierarchical clustering on drugT profiles (columns in the final plot)
## Use the DGE slice because it is cleaner and less saturated
DM <- R3 %>% filter( source == "DGE" ) %>% select( name_query, pert_iname, tau ) %>%
    spread( name_query, tau ) %>% as.data.frame %>% column_to_rownames("pert_iname")
comp_order <- function(m) {
  dm <- dist(m)
  hclust(dm) %>% reorder(dm) %>%  dendextend::order.hclust() %>% labels(dm)[.]
}
lvl <- comp_order(DM)
lvl2 <- R2 %>%
  filter( source == "DGE" ) %>%
  distinct(name_query, dataset) %>%
  group_by(dataset) %>%
  group_map(
    ~DM[, unique(.x[["name_query"]])] %>%
      t() %>%
      comp_order()
  ) %>%
  {c(.[[2]], "", .[[1]])}

## Fix the order via factor levels
R3 <- R3 %>%
  bind_rows(
    tibble(
      name_query = "",
      pert_iname = unique(.[["pert_iname"]]),
      tau = NA_real_
    )
  ) %>%
  mutate(name_query = factor(name_query, lvl2),
                    pert_iname = factor(pert_iname, lvl))

# # Complete missing observations at z-scores that yielded insufficient
# # genes for Clue with NA
# R2_completed <- bind_rows(
#     R2 %>%
#         filter(source == "DGE"),
#     R2 %>%
#         filter(source == "L1000") %>%
#         complete(nesting(idQ, idT, source, drugT, drugQ), z_score_cutoff)
# )

## Plotting elements
pal <- rev(RColorBrewer::brewer.pal(n=7, name="RdBu"))
etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
theme_bold <- function() {
    theme(axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
          axis.text.y = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          axis.ticks = element_blank())
}

## Plotting a heatmap of clue hits
fplot <- function(X) {
    ggplot( X, aes(x=name_query, y=pert_iname, fill=tau) ) +
        theme_minimal() + theme_bold() +
        geom_tile(color="black") +
        # geom_tile(data=filter(X, idQ==idT), color="black", size=1) +
        scale_fill_gradientn( colors=pal, limits=c(-100,100), na.value = "white" ) +
        labs(x = "Drug query", y = "Clue target class", fill = "Tau" )
}

ggsave(
  file.path(wd, "dub_sr_repurposing_unknown_drugs_pcl.png"),
  fplot(R3),
  width = 9, height = 10
)
```



```{r dub_ad_repurposing_genetic_pertubations}
R <- clue_res_combined %>%
    filter( result_type == "pert", score_level == "summary" ) %>%
    pluck( "data", 1 )


## Identify relevant gene sets
dubs <- deseq_res %>%
  mutate(
    gene_set = condition_conc %>%
      str_replace_all("\\s", "_") %>%
      str_replace_all("[^\\w]", "")
  ) %>%
  inner_join(
    dge_meta %>%
        unnest(meta) %>%
        mutate(
          query_group = case_when(
            lspci_id %in% c(91047, 93750) ~ "controls",
            !lspci_id %in% signature_meta$lspci_id ~ paste("unknowns", dataset, sep = " "),
            TRUE ~ NA_character_
          )
        ) %>%
        filter(
          !is.na(query_group),
          dataset %in% c("sr_repurposing", "ld_dub", "lincs_cdk4_6_7"),
          is.na(stim)
        ) %>%
        group_by(query_group, dataset, cells, drug_id) %>%
        arrange(desc(time)) %>%
        slice(1) %>%
        select(query_group, cells, drug_id, time, stim, dataset),
    by = c("cells", "drug_id", "time", "stim")
  )

## Isolate the appropriate slice of data
## Aggregate across multiple entries to compute master similarity score
R2 <- R %>%
  drop_na(tau) %>%
  # filter(pert_type == "trt_cp") %>%
  inner_join(
    dubs %>%
      distinct(query_group, gene_set, drug_id, dataset),
    by = "gene_set"
  ) %>%
  # dplyr::rename(pert_iname = id) %>%
  group_by( query_group, pert_type, pert_iname, name_query, source, z_score_cutoff ) %>%
  summarize_at(
    "tau", ~quantile(.x, c(0.67, 0.33), names = FALSE) %>%
                {.[order(abs(.))[2]]}
    # "tau", ~.x[ which.max(abs(.x)) ]
  ) %>%
  ungroup() %>%
  mutate_at( "source", toupper )

# FInd most similar drugs per query

R_only_genetic <- R2 %>%
  filter(pert_type %in% c("trt_oe", "trt_sh.cgs")) %>%
  mutate(
    pert_iname = paste(pert_iname, pert_type, sep = "_") %>%
      str_replace(fixed("_trt_oe"), " OE") %>%
      str_replace(fixed("_trt_sh.cgs"), " KD")
  )

R3 <- R_only_genetic %>%
  dplyr::filter(
    pert_iname %in% {
      # inner_join(
      #   .,
      #   group_by(., pert_iname) %>%
      #     summarize(
      #       mean_per_pert = mean(tau)
      #     ),
      #   by = "pert_iname"
      # ) %>%
      #   mutate(
      #     mean_diff = abs(tau - mean_per_pert)
      #   ) %>%
      #   filter(abs(tau) > 80) %>%
      #   group_by(name_query) %>%
      #   arrange(desc(mean_diff)) %>%
      #   slice(1:10) %>%
      #   ungroup() %>%
      #   pull(pert_iname)
      # group_by(., pert_iname) %>%
      #   summarize(
      #     pert_iname_var = var(tau, na.rm = TRUE)
      #   ) %>%
      #   ungroup() %>%
      #   arrange(desc(pert_iname_var)) %>%
      #   head(50) %>%
      #   pull(pert_iname)
      group_by(., name_query) %>%
        arrange(desc(abs(tau)), .by_group = TRUE) %>%
        slice(1:10) %>%
        ungroup() %>%
        pull(pert_iname)
    }
    # pert_iname %in% {
    #   mean_tau_by_pert <- group_by(., pert_iname) %>%
    #     summarize(mean_tau = mean(tau), .groups = "drop")
    #   inner_join(., mean_tau_by_pert, by = "pert_iname") %>%
    #     group_by(name_query) %>%
    #     mutate(abs_tau_diff = abs(tau - mean_tau)) %>%
    #     arrange(desc(abs_tau_diff), .by_group = TRUE) %>%
    #     slice(1:6) %>%
    #     ungroup() %>%
    #     pull(pert_iname)
    # }
  )


## Perform hierarchical clustering on drugT profiles (columns in the final plot)
## Use the DGE slice because it is cleaner and less saturated
DM <- R3 %>%
  filter( source == "DGE" ) %>%
  select(
    name_query,
    pert_iname,
    tau
  ) %>%
  spread( name_query, tau ) %>%
  as.data.frame %>%
  column_to_rownames("pert_iname")

comp_order <- function(clust) {
  dm <- clust %>%
    dist()
  dm %>%
    hclust() %>%
    reorder(dm) %>%
    labels()
}

DM_clust <- DM %>%
  dist() %>%
  hclust() %>%
  reorder(dist(DM))

lvl <- DM_clust %>%
  labels()

# split_vector <- cutree(DM_clust, k = 2)
split_vector <- set_names(
  rep(c(1, 2), each = ceiling(length(lvl) / 2), length.out = length(lvl)),
  lvl
)

lvl2 <- R2 %>%
  filter( source == "DGE" ) %>%
  distinct(name_query, query_group) %>%
  group_by(query_group) %>%
  group_map(
    function(.x, ...) {
      queries <- unique(.x[["name_query"]])
      if (length(queries) == 1)
        return(queries)
      DM[, queries] %>%
        t() %>%
        comp_order()
    }
  ) %>%
  # Add blank spaces between datasets
  {
    imap(
      .,
      ~c(.x, strrep(" ", .y))
    ) %>%
      {
        exec(c, !!!.)
      }
  }

## Fix the order via factor levels
R3 <- R3 %>%
  bind_rows(
    crossing(
      name_query = setdiff(lvl2, unique(R3[["name_query"]])),
      pert_iname = unique(.[["pert_iname"]]),
      tau = NA_real_
    )
  ) %>%
  mutate(
    # Horizontal facet split unite the second and third dendrogram cut
    split_group = split_vector[pert_iname] %>%
      as.character(),
      # recode("2" = "3"),
    name_query = factor(name_query, lvl2),
    pert_iname = factor(pert_iname, lvl)
  )

# # Complete missing observations at z-scores that yielded insufficient
# # genes for Clue with NA
# R2_completed <- bind_rows(
#     R2 %>%
#         filter(source == "DGE"),
#     R2 %>%
#         filter(source == "L1000") %>%
#         complete(nesting(idQ, idT, source, drugT, drugQ), z_score_cutoff)
# )


# Highlight specific pertubations with boxes
# 
# highlight_pertubations <- tribble(
#   ~pertubation, ~group,
#   "CDK6 OE", "control",
#   "PSMD2 KD", "proteasome",
#   "PSMA3 KD", "proteasome",
#   "PSMA1 KD", "proteasome",
#   "PSMB2 KD", "proteasome",
#   "PSMD4 KD", "proteasome",
#   "CDK4 KD", "control",
#   "PSMD1 KD", "proteasome",
#   "PTPN2 KD", "lorlatinib",
#   "INPPL1 KD", "lorlatinib"
# ) %>%
#   mutate(across(pertubation, factor, levels = levels(R3[["pert_iname"]]))) %>%
#   mutate(across(group, factor)) %>%
#   mutate(
#     color = {
#       highlight_colors <- levels(.[["group"]]) %>% {
#         palette.colors(
#           n = length(.),
#           palette = "Tableau 10"
#         ) %>%
#           set_names(.)
#       }
#       highlight_colors[group]
#     }
#   )
# 
# palette.colors(n = 3, "Tableau 10")

## Plotting elements
pal <- rev(RColorBrewer::brewer.pal(n=7, name="RdBu"))
etxt <- function(s, ...) {element_text( size = s, face = "bold", ... )}
theme_bold <- function() {
    theme(axis.text.x = etxt(12, angle=90, hjust=1, vjust=0.5),
          axis.text.y = etxt(12), axis.title = etxt(14),
          legend.text = etxt(12), legend.title = etxt(14),
          axis.ticks = element_blank())
}

## Plotting a heatmap of clue hits
fplot <- function(X, highlight_pertubations) {
  # highlight_palette <- with(
  #   highlight_pertubations,
  #   set_names(unique(color), unique(group))
  # ) %>%
  #   c(" " = "black") 
  # X <- X %>%
  #   left_join(
  #     highlight_pertubations %>%
  #       select(pertubation, border_color = color),
  #     by = c("pert_iname" = "pertubation")
  #   ) %>%
  #   mutate(
  #     border_color = case_when(
  #       str_detect(name_query, "^( )+$") ~ NA_character_,
  #       !is.na(border_color) ~ border_color,
  #       TRUE ~ "#000000"
  #     ),
  #     border_size = if_else(
  #       pert_iname %in% 
  #     )
  #   )
  ggplot(
    # Arrange just so that cells with border are drawn last for clean rendering
    X %>% arrange(!str_detect(name_query, "^( )+$")),
    aes(x=name_query,
        y=pert_iname,
        fill=tau)
    )+
      theme_minimal() + theme_bold() +
      geom_tile(
        aes(color = str_detect(name_query, "^( )+$"))
      ) +
      # Remove cell borders in empty space between left and right side
      scale_color_manual(
        values = c("TRUE" = NA_character_, "FALSE" = "black"),
        guide = FALSE
      ) +
      scale_fill_gradientn( colors=pal, limits=c(-100,100), na.value = "white" ) +
      labs(x = "Drug query", y = "Clue target class", fill = "Tau" ) +
      facet_wrap(~split_group, scales = "free_y") +
      # Remove facet labels
      theme(strip.background = element_blank(), strip.text.x = element_blank())
}

ggsave(
  file.path(wd, "dub_sr_repurposing_unknown_drugs_genetic_pert_top6_abs_tau_genetic_including_controls_2.pdf"),
  fplot(R3, highlight_pertubations),
  width = 10, height = 13
)

fplot_horizontal <- function(X) {
    ggplot(
      # Arrange just so that cells with border are drawn last for clean rendering
      X %>% arrange(name_query != ""),
      aes(y=name_query,
          x=pert_iname,
          fill=tau)
      )+
        theme_minimal() + theme_bold() +
        geom_tile(
          aes(color = name_query == "")
        ) +
        # Remove cell borders in empty space between left and right side
        scale_color_manual(
          values = c("TRUE" = NA_character_, "FALSE" = "black"),
          guide = FALSE
        ) +
        scale_fill_gradientn( colors=pal, limits=c(-100,100), na.value = "white" ) +
        labs(y = "Drug query", x = "Clue target class", fill = "Tau" )
}

ggsave(
  file.path(wd, "dub_sr_repurposing_unknown_drugs_genetic_pert_top6_abs_tau_genetic_horizontal.pdf"),
  fplot_horizontal(R3),
  width = 16, height = 4
)


```
