---
title: "Upload CDK data to synapse"
author: "Clemens Hug"
date: "3/14/2019"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(cmapR)
library(patchwork)
library(egg)

paste_ <- function(...) {
  paste(..., sep = "_")
}

theme_set(theme_bw())

synapser::synLogin()

syn <- synExtra::synDownloader( "~/data/AMP-AD/figs" )
```

## Preprocessed CDK data

```{r loading}
cdk_meta_combined <- readr::read_csv(file.path("..", "wrangled", "cdk_meta_combined.csv"))

ensembl_gene_id_mapping <- readr::read_csv(file.path("wrangled", "ensembl_gene_id_mapping.csv"))

sample_subsets_list <- readr::read_rds(file.path("sample_matching", "sample_subsets_list.rds"))

deseq <- readr::read_rds(file.path("deseq", "deseq_datasets.rds"))
counts <- readr::read_csv(file.path("deseq", "count_data.csv.gz"))

ensembl_gene_id_mapping <- readr::read_csv(file.path("wrangled", "ensembl_gene_id_mapping.csv")) 

l1000 <- readr::read_csv(file.path("wrangled", "l1000_gene_list.csv"))
l1000_ensembl_gene_ids <- l1000 %>%
  dplyr::left_join(ensembl_gene_id_mapping, by = c("gene_symbol" = "symbol")) %>%
  tidyr::drop_na(ensembl_gene_id) %>%
  .$ensembl_gene_id
```


```{r write_to_synapse}
amp_data_syn_id <- "syn11615748"
sm_wrangling_activity <- synapser::Activity(
  name = "Wrangling small molecule suite data",
  used = c(
    "https://raw.githubusercontent.com/sorgerlab/smallmoleculesuite/8ddbd6957d877f4ec13baca0b222d6c32cc1f9fa/LibraryR/gene_lists/Full_LigandedGenome_20171217.txt",
    "https://raw.githubusercontent.com/sorgerlab/smallmoleculesuite/8ddbd6957d877f4ec13baca0b222d6c32cc1f9fa/SimilaritySelectR/input/affinity_selectivity_table_ChemblV22_1_20170804.csv",
    "https://raw.githubusercontent.com/sorgerlab/smallmoleculesuite/8ddbd6957d877f4ec13baca0b222d6c32cc1f9fa/SimilaritySelectR/input/similarity_table_ChemblV22_1_20170804.csv",
    "https://www.biorxiv.org/highwire/filestream/108838/field_highwire_adjunct_files/1/358978-10.csv",
    "syn11801537"
  ),
  executed = "https://github.com/clemenshug/amp-ad/blob/target_gene_profile_tas/plots/figs/Fig4/wrangling/Small%20molecule%20suite.Rmd"
)

sm_wrangling_folder <- synapser::Folder(name = "small_molecule_suite", parent = amp_data_syn_id) %>%
  synapser::synStore() %>%
  .$properties %>%
  .$id
sm_files <- list.files(file.path("..", "wrangled", "small_molecule_suite"), full.names = TRUE)

sm_files %>%
  purrr::map(
    function (p) {
      f <- synapser::File(
        p,
        parent = sm_wrangling_folder
      )
      synapser::synStore(f, activity = sm_wrangling_activity)
    }
  )

```
