
```{r setup}
library(tidyverse)
library(synExtra)
library(biomaRt)

synapser::synLogin()
syn <- synExtra::synDownloader("~/data/DGE_comp/")
syn_csv <- function(synid, ...) {
  syn(synid) %>%
    readr::read_csv(...)
}
syn_tsv <- function(synid, ...) {
  syn(synid) %>%
    readr::read_tsv(...)
}
paste_ <- function(...) {
  paste(..., sep = "_")
}
```

## Goal

Load and process RNA-seq counts from the DUB inhibitor experiment perfomed
by Laura Doherty.
https://www.synapse.org/#!Synapse:syn13363863


## Preprocessed

The DGE and bulk RNA-seq data was already aligned and preprocessed, loading data from:

CDK4/6 inhibitor dataset collected by Caitlin Mills

* DGE Counts matrix:  syn12612304
* DGE well map: syn12979088


```{r loading_datasets}
dub_dge_meta <- syn_tsv("syn12979088") %>%
  dplyr::rename(cell_line = cellline, drug = agent) %>%
  dplyr::select(-column, -row, -plate) %>%
  dplyr::mutate(
    sample_id = paste("dub", "dge", cell_line, drug, concentration, time, well, sep = "_"),
    batch = "dge_1",
    method = "dge"
  )

dub_dge_counts <- syn_tsv("syn12612304") %>%
  dplyr::select(-HUGO) %>%
  dplyr::rename(ensembl_gene_id = ENSEMBL) %>%
  tidyr::gather(well, count, -ensembl_gene_id) %>%
  # As per the description at syn13363863, removing P11_old (119 counts), P11_new2 (673 counts)
  # and keeping only P11_new1 (227,020 counts)
  dplyr::filter(!(well %in% c("P11_new2", "P11_old"))) %>%
  dplyr::mutate(well = recode(well, P11_new1 = "P11")) %>%
  dplyr::left_join(dub_dge_meta %>% dplyr::select(well, sample_id), by = "well") %>%
  dplyr::select(sample_id, ensembl_gene_id, count)

dub_gene_symbols <- dub_dge_counts$ensembl_gene_id %>%
  unique() %>%
  genebabel::query_hgnc(c("ensembl_gene_id")) %>%
  drop_na(symbol)

dub_gene_symbols %>%
  dplyr::count(query) %>%
  dplyr::count(n)
# No ensembl gene ids maap to multiple symbols, good!

dub_dge_counts <- dub_dge_counts %>%
  inner_join(dplyr::select(dub_gene_symbols, ensembl_gene_id = query, symbol), by = "ensembl_gene_id")

```


```{r writing_data_disk}
dub_dir <- file.path("..", "wrangled", "dub")
dir.create(dub_dir, showWarnings = FALSE)

readr::write_csv(dub_dge_meta, file.path(dub_dir, "dub_dge_meta.csv"))
readr::write_csv(dub_dge_counts, file.path(dub_dir, "dub_dge_counts.csv.gz"))

readr::write_csv(dub_dge_meta, file.path(dub_dir, "meta.csv"))
readr::write_csv(dub_dge_counts, file.path(dub_dir, "counts.csv.gz"))
```
